name: 'CI'

on:
  push:
    branches:
      - main
    paths-ignore: [ '**.md' ]
  pull_request:
    paths-ignore: [ '**.md' ]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  py-flask-ci:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Python Flask Build
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.11

      - name: Install requirements
        run: |
            pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest --cov-report term-missing --cov=project

      - name: Save AppMaps
        uses: actions/cache@v3
        if: always()
        with:
          path: ./tmp/appmap
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

  appmap-analysis:
    if: always()
    needs: [ py-flask-ci ]
    uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
    permissions:
      actions: read
      contents: read
      checks: write
      pull-requests: write
