name: 'CI'

on:
  pull_request:
    paths-ignore: [ '**.md' ]
  push:
    paths-ignore: [ '**.md' ]
    branches:
      - main
  workflow_dispatch:

jobs:
  py-flask-ci:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Python Flask Build
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.11

      - name: Install requirements
        run: |
            pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest --cov-report term-missing --cov=project